# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18a6290b003a390ef8fe267f819cc7ac7ff7f88723f55af1ba3ca7a4a455d2faef3fbcd92cf8cf365fd395df66c18ba1642cd58b7ce0b75612234bd62a914cab

test:
  secret_key_base: 07df43de41f39eeb56df6439b5cec16a8a3a859fa8a97347eb444b4dbec2c17e84f79ccca24bf9b67636349a81338cf4839af931fe570fe992fe525135127857

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
